include:
  - board: nice_nano//zmk
    revision: v2
    shield: lily58_left nice_view_adapter nice_view
  - board: nice_nano//zmk
    revision: v2
    shield: lily58_right nice_view_adapter nice_view_custom
  - board: nice_nano//zmk
    revision: v2
    shield: settings_reset
